archive_name = SpiderPig
mod_id = spig
mod_group = com.lupicus.spig
mod_version = 1.0.4
mc_version = 26.1
forge_version = 62.0.4

org.gradle.daemon=false
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true

org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn

net.minecraftforge.gradle.merge-source-sets=true
